version: '3.8'

services:
  spark-master:
    image: bitnami/spark:3.4
    networks:
      - code-with-deposit
    environment:
      SPARK_MODE: master
      SPARK_RPC_AUTHENTICATION_ENABLED: no
      SPARK_RPC_ENCRYPTION_ENABLED: no
      SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED: no
      SPARK_SSL_ENABLED: no
    ports:
      - "8090:8080"
      - "7077:7077"
    volumes:
      - ./data:/data

  spark-worker:
    image: bitnami/spark:3.4
    networks:
      - code-with-deposit
    environment:
      SPARK_MODE: worker
      SPARK_MASTER_URL: spark://spark-master:7077
      SPARK_WORKER_MEMORY: 1G
      SPARK_WORKER_CORES: 1
      SPARK_RPC_AUTHENTICATION_ENABLED: no
      SPARK_RPC_ENCRYPTION_ENABLED: no
      SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED: no
      SPARK_SSL_ENABLED: no
    depends_on:
      - spark-master
    volumes:
      - ./data:/data

  jupyter:
    build:
      context: .
      dockerfile: Dockerfile_template
    networks:
      - code-with-deposit
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/hdb/work
      - ./data:/home/hdb/data
    environment:
      - SPARK_HOME=/opt/spark
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_DRIVER_MEMORY=1g
      - SPARK_EXECUTOR_MEMORY=1g
      - PYTHONPATH=/opt/spark/python:/opt/spark/python/lib/py4j-0.10.9.7-src.zip
      - PYSPARK_PYTHON=python3
      - JUPYTER_ENABLE_LAB=yes
    command: jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root
    depends_on:
      - spark-master

networks:
  code-with-deposit:
    driver: bridge